# This is the default format. 
# For more see: https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /:year/:month/:title 
markdown: kramdown

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", "cache", "figure"]
pygments: true

# Themes are encouraged to use these universal variables 
# so be sure to set them if your theme uses them.
#
title : Washington State SGP Analyses
tagline: Resources and Documentation
author :
  name : Center For Assessment
  email : http://www.nciea.org
  github : CenterForAssessment

# The production_url is only used when full-domain names are needed
# such as sitemap.txt 
# Most places will/should use BASE_PATH to make the urls
#
# If you have set a CNAME (pages.github.com) set your custom domain here.
# Else if you are pushing to username.github.com, replace with your username.
# Finally if you are pushing to a GitHub project page, include the project name at the end.
#
# production_url : Washington

# All Jekyll-Bootstrap specific configurations are namespaced into this hash
#
JB :
  version : 0.3.0

  # All links will be namespaced by BASE_PATH if defined.
  # Links in your website should always be prefixed with {{BASE_PATH}}
  # however this value will be dynamically changed depending on your deployment situation.
  #
  # CNAME (http://yourcustomdomain.com)
  #   DO NOT SET BASE_PATH 
  #   (urls will be prefixed with "/" and work relatively)
  #
  # GitHub Pages (http://username.github.com)
  #   DO NOT SET BASE_PATH 
  #   (urls will be prefixed with "/" and work relatively)
  #
  # GitHub Project Pages (http://username.github.com/project-name)
  #
  #   A GitHub Project site exists in the `gh-pages` branch of one of your repositories.
  #  REQUIRED! Set BASE_PATH to: http://username.github.com/project-name
  #
  # CAUTION:
  #   - When in Localhost, your site will run from root "/" regardless of BASE_PATH
  #   - Only the following values are falsy: ["", null, false]
  #   - When setting BASE_PATH it must be a valid url.
  #     This means always setting the protocol (http|https) or prefixing with "/"
  BASE_PATH : http://centerforassessment.github.io/Washington

  # By default, the asset_path is automatically defined relative to BASE_PATH plus the enabled theme.
  # ex: [BASE_PATH]/assets/themes/[THEME-NAME]
  #
  # Override this by defining an absolute path to assets here.
  # ex: 
  #   http://s3.amazonaws.com/yoursite/themes/watermelon
  #   /assets
  #
  # ASSET_PATH : assets/themes/CFA

  # These paths are to the main pages Jekyll-Bootstrap ships with.
  # Some JB helpers refer to these paths; change theme here if needed.
  #
  #archive_path: /archive.html
  #categories_path : /categories.html
  #tags_path : /tags.html
  #atom_path : /atom.xml
  #rss_path : /rss.xml

  # Settings for comments helper
  # Set 'provider' to the comment provider you want to use.
  # Set 'provider' to false to turn commenting off globally.
  #
  #  comments :
  #    provider : disqus
  #    disqus :
  #      short_name : washington_sgp
   
  # Settings for analytics helper
  # Set 'provider' to the analytics provider you want to use.
  # Set 'provider' to false to turn analytics off globally.
  #        
  # analytics :
  #   provider : google 
  #   google : 
  #     tracking_id : 'UA-XXXXXXXX-Y'

  # Settings for sharing helper. 
  # Sharing is for things like tweet, plusone, like, reddit buttons etc.
  # Set 'provider' to the sharing provider you want to use.
  # Set 'provider' to false to turn sharing off globally.
  #
  sharing :
    provider : false
    
navbar: 
  - 
    name: Resources
    menu: 
      - 
        label: Annual Analysis Reports <b class='caret'></b>
        submenu: 
          - 
            label: School Year 2011-12
            link: Washington_SGP_Analysis_2012.html
          - 
            label: School Year 2012-13
            link: 404.html
      - 
        label: OSPI Documentation <b class='caret'></b>
        submenu: 
          - 
            label: SGP Business Rules
            link: http://www.k12.wa.us/Assessment/pubdocs/BusinessRulesforCalculationofWashingtonSGP.pdf
      - 
        label: FAQ
        link: FAQ.html 

  - 
    name: Technical Documentation
    menu: 
      - 
        label: The Washington Growth Model
        link: Washington_SGP_Model.html 
      - 
        label: Published Articles <b class='caret'></b>
        submenu: 
          - 
            label:  Norm- and criterion-referenced student growth.<br> Betebenner, EMIP 2009
            link:  resources/Betebenner_EMIP_2009.pdf
      - 
        label: White Papers
        submenu: 
          - 
            label: Norm- and Criterion-Referenced Student Growth <br> Betebenner 2008
            link: http://www.nciea.org/publication_PDFs/normative_criterion_growth_DB08.pdf
          - 
            label: Growth Standards & Accountability <br> Betebenner 2009
            link: http://www.nciea.org/publication_PDFs/growthandStandard_DB09.pdf
          - 
            label: Student Growth Percentiles and Shoe Leather <br> Betebenner, Wenning & Briggs 2011
            link: http://www.nciea.org/publication_PDFs/growthandStandard_DB09.pdf

  -
    name: How it Works 
    menu: 
      - 
        label: Analytic Software <b class='caret'></b>
        submenu:
          - 
            label: SGP Package Primer
            link: resources/sgpPrimer.pdf
          - 
            label: SGP Demonstrations
            link: 404.html
      - 
        label: Data Prep and Structure
        link: https://github.com/CenterForAssessment/SGP#data-preparation
      - 
        label: Presentations & Trainings <b class='caret'></b>
        submenu: 
          - 
            label: R and the SGP Package
            link: resources/R+SGP_Package.pdf
          - 
            label: NCME Presentation
            link: 404.html

  -
    name: About Us 
    menu: 
      - 
        label: Center for Assessment (NCIEA)
        link: http://www.nciea.org/
      - 
        label: Washington Office of Superintendent of Public Instruction (OSPI)
        link: http://www.k12.wa.us/Assessment/StudentGrowth.aspx

  -
    name: Contact Us 
    link: 404.html

  # Special section for CFA theme - 'footer social' 
  # Puts social icons/links into each "post" footer section along with the copyright info.
footer_social:
  - type: GitHub
    link: https://github.com/CenterForAssessment
    image: images/social-icon/github.png

  - type: Twitter
    link: http://twitter.com/DBetebenner
    image: images/social-icon/twitter.png

copyright: "CopyrightÂ© 2013 National Center for the Improvement of Educational Assessment. All rights reserved. This site is powered by Jekyll and hosted on GitHub Pages using the CFA theme for Jekyll Bootstrap."

  # Settings for all other include helpers can be defined by creating 
  # a hash with key named for the given helper. ex:
  #
  #   pages_list :
  #     provider : "custom"   
  #
  # Setting any helper's provider to 'custom' will bypass the helper code
  # and include your custom code. Your custom file must be defined at:
  #   ./_includes/custom/[HELPER]
  # where [HELPER] is the name of the helper you are overriding.
  
